package com.maids.LMS.enums;

public enum ErrorCode {
    UNKNOWN_ERROR,
    NOT_VALID,
    DUPLICATE_RESOURCE,
    INVALID_OPERATION,
    EXTERNAL_SERVICE_ERROR,
    RATE_LIMIT_EXCEEDED,
    RESOURCE_NOT_FOUND,
}
